# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4DSfjMc-H1xxxrgsvJOAOX-O7dC6F_j
"""

from flask import Flask, render_template
import requests
import pandas as pd
from datetime import datetime
import pytz

app = Flask(__name__)

# Konfigurasi Parameter PLTS & Lokasi (Pasuruan)
LAT = -7.6453
LON = 112.9075
CAPACITY_MWP = 1.5
TEMP_COEFF = -0.004
NOCT = 45
INVERTER_EFF = 0.85

@app.route('/')
def index():
    # Sinkronisasi Waktu Lokal WIB
    wib_tz = pytz.timezone('Asia/Jakarta')
    now_wib = datetime.now(wib_tz)
    today_str = now_wib.strftime('%Y-%m-%d')

    # Ambil Data Real-time dari Open-Meteo API
    url = f"https://api.open-meteo.com/v1/forecast?latitude={LAT}&longitude={LON}&hourly=shortwave_radiation,temperature_2m,weathercode&timezone=auto&start_date={today_str}&end_date={today_str}"

    try:
        response = requests.get(url, timeout=10)
        data = response.json()
        hourly_data = data['hourly']
    except Exception as e:
        return f"Gagal mengambil data dari API: {e}"

    # Parsing Data DataFrame
    df = pd.DataFrame({
        'time': pd.to_datetime(hourly_data['time']),
        'ghi': hourly_data['shortwave_radiation'],
        'temp_ambient': hourly_data['temperature_2m']
    })

    if df['time'].dt.tz is None:
        df['time'] = df['time'].dt.tz_localize('Asia/Jakarta')
    else:
        df['time'] = df['time'].dt.tz_convert('Asia/Jakarta')

    # Kalkulasi Daya PLTS
    def calculate_power(row):
        ghi = row['ghi']
        temp_amb = row['temp_ambient']
        if pd.isna(ghi) or ghi <= 0:
            return 0.0
        temp_cell = temp_amb + (NOCT - 20) * (ghi / 800.0)
        temp_factor = 1 + TEMP_COEFF * (temp_cell - 25)
        power_mw = CAPACITY_MWP * (ghi / 1000.0) * temp_factor * INVERTER_EFF
        return max(0.0, power_mw)

    df['power_mw'] = df.apply(calculate_power, axis=1)
    df['history_baseline_mw'] = df['ghi'] * (CAPACITY_MWP / 1000.0) * INVERTER_EFF

    # Batasi data real-time hanya sampai jam saat ini
    df_filtered = df[df['time'] <= now_wib].copy()

    # Format data untuk dikirim ke Chart.js di HTML
    labels = df['time'].dt.strftime('%H:%M').tolist()
    realtime_power = [p if t <= now_wib else None for p, t in zip(df['power_mw'], df['time'])]
    baseline_power = df['history_baseline_mw'].tolist()

    table_data = df_filtered[['time', 'ghi', 'temp_ambient', 'power_mw']].to_dict(orient='records')

    return render_template('index.html',
                           labels=labels,
                           realtime=realtime_power,
                           baseline=baseline_power,
                           today=today_str,
                           now_time=now_wib.strftime('%H:%M'),
                           table_data=table_data)

if __name__ == '__main__':
    # Host '0.0.0.0' agar bisa diakses via LAN/Wi-Fi dari perangkat lain
    app.run(host='0.0.0.0', port=5000, debug=False)